# Generated by Django 4.2.5 on 2023-09-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_defaultuser_avatar_img_alter_myuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audiobooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=1200)),
                ('audio_book', models.FileField(upload_to='audio')),
                ('book_img', models.ImageField(upload_to='book_img')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contentmaker')),
                ('genres', models.ManyToManyField(to='audiobooks.genre')),
            ],
        ),
    ]
