# Generated by Django 4.2.5 on 2023-10-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0006_pendingaudiobooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobooks',
            name='created_by',
        ),
    ]
