# Generated by Django 4.2.5 on 2023-10-05 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiobooks', '0007_remove_audiobooks_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobooks',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_audiobooks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
