# Generated by Django 4.2.5 on 2023-10-05 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiobooks', '0008_audiobooks_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobooks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_audiobooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
