# Generated by Django 4.2.5 on 2023-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_contentmaker_avatar_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='avatar_img',
            field=models.ImageField(default='default-avatar.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=55, unique=True, verbose_name='username'),
        ),
    ]
