# Generated by Django 4.2.5 on 2023-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_seller_myuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmaker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentmaker',
            name='reason_to_become_contentmaker',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
