# Generated by Django 4.2.5 on 2023-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_contentmaker_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmaker',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='contentmaker',
            name='reason_to_become_contentmaker',
        ),
        migrations.AddField(
            model_name='contentmaker',
            name='avatar_img',
            field=models.ImageField(default='default-avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
