# Generated by Django 4.2.5 on 2023-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_contentmaker_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmaker',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmaker',
            name='avatar_img',
            field=models.ImageField(default='default-avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
