# Generated by Django 4.2.5 on 2023-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
