# Generated by Django 4.2.5 on 2023-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_pendingbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingbook',
            name='book_img',
            field=models.ImageField(upload_to='rbook_img'),
        ),
        migrations.AlterField(
            model_name='pendingbook',
            name='description',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='pendingbook',
            name='price',
            field=models.IntegerField(),
        ),
    ]
