# Generated by Django 4.2.5 on 2023-10-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_basket_basketitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user',
            new_name='defaultuser',
        ),
    ]
