# Generated by Django 4.2.5 on 2023-10-06 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0009_alter_audiobooks_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_remove_basket_defaultuser_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='audiobooks.genre'),
        ),
        migrations.AlterField(
            model_name='pendingbook',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
